# Generated by Django 4.2.15 on 2024-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='privacy_settings',
            field=models.CharField(choices=[('PV', 'Private'), ('PB', 'Public')], max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
