# Generated by Django 4.2.15 on 2024-09-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_board_category_alter_board_privacy_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
        migrations.AlterField(
            model_name='board',
            name='privacy_settings',
            field=models.CharField(choices=[('PV', 'Private'), ('PB', 'Public')], max_length=2),
        ),
    ]
