# Generated by Django 4.2.15 on 2024-09-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_board_category_alter_board_privacy_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
