# Generated by Django 5.1.1 on 2024-09-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('border_color', models.CharField(max_length=10)),
                ('coordinates', models.JSONField()),
            ],
        ),
    ]
