# Generated by Django 5.1.1 on 2024-11-25 22:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
