# Generated by Django 5.1.1 on 2024-11-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='border_color',
            field=models.CharField(max_length=100),
        ),
    ]
