# Generated by Django 5.1.3 on 2024-11-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_category_category_slug_alter_board_description'),
        ('note', '0004_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board'),
        ),
    ]
