# Generated by Django 4.2.15 on 2024-11-25 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('facebook_link', models.TextField(blank=True, max_length=250, null=True)),
                ('facebook_link_hidden', models.BooleanField(default=True, null=True)),
                ('linkedin_link', models.TextField(blank=True, max_length=250, null=True)),
                ('linkedin_link_hidden', models.BooleanField(default=True, null=True)),
                ('twitter_link', models.TextField(blank=True, max_length=250, null=True)),
                ('twitter_link_hidden', models.BooleanField(default=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
