# Generated by Django 5.1.1 on 2024-10-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='instagram_link',
            new_name='twitter_link',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='instagram_link_hidden',
            new_name='twitter_link_hidden',
        ),
    ]
