# Generated by Django 5.1.1 on 2024-10-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='privacy_settings',
        ),
        migrations.AddField(
            model_name='board',
            name='board_theme',
            field=models.CharField(choices=[('white', 'Default (White)'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='board',
            name='board_type',
            field=models.CharField(choices=[('simple', 'Simple Board'), ('project', 'Project Board')], default='simple', max_length=10),
        ),
        migrations.AddField(
            model_name='board',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7),
        ),
    ]
