"""
Django settings for Stick_It project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
# from secret import get_decrypted_password
import os #for static not yet researched further
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9ptvl+lq23$w4&**#*!xx$oz(2a#4zt31m%-vjnbbivfny3lhd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'note',
    'authentication',
    'mainApp',
    'board',
    
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'authentication.backends.EmailBackend'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Stick_It.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Stick_It.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'Stick-It-Database',
#         'USER': 'root',
#         'PASSWORD': 'elijahgwapo',
#         # 'PASSWORD': get_decrypted_password(),
#         'HOST' : 'localhost',
#         'PORT' : '3306'        
#     }
# }
DATABASES = {
    "default": {
# <<<<<<< homepage-with-create-board
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Stick-It-Database',
        'USER': 'root',
        'PASSWORD': 'mysqlroot00',
        # 'PASSWORD': get_decrypted_password(),
        'HOST' : 'localhost',
        'PORT' : '3307'
# =======
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": "mydatabase",
# >>>>>>> main
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# more nottes
# https://www.geeksforgeeks.org/django-static-file/

STATIC_URL = 'static/'
MEDIA_URL = 'images/'

#https://www.youtube.com/watch?v=Sd-RseDuy-c cuz i cant load the css

# LIST DOWN ALL THE STATIC FILES IN DIS DIRECTORY
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR,'static'),
    ('authentication', os.path.join(BASE_DIR, 'authentication/static')),
    ('note', os.path.join(BASE_DIR, 'note/static')),
    ('board',os.path.join(BASE_DIR,'board/static')),
]
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images')
STATIC_ROOT = os.path.join(BASE_DIR,'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/' 
MEDIA_ROOT = BASE_DIR / 'media' 