# Generated by Django 4.2.15 on 2024-10-29 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('board_type', models.CharField(choices=[('simple', 'Simple Board'), ('project', 'Project Board')], default='simple', max_length=10)),
                ('board_theme', models.CharField(choices=[('white', 'Default (White)'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink')], default='white', max_length=10)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
                ('category_description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBoard',
            fields=[
                ('board_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.board')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'project_board',
            },
            bases=('board.board',),
        ),
        migrations.CreateModel(
            name='SimpleBoard',
            fields=[
                ('board_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.board')),
            ],
            options={
                'db_table': 'simple_board',
            },
            bases=('board.board',),
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.category'),
        ),
        migrations.AddField(
            model_name='board',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
