# Generated by Django 4.2.15 on 2024-11-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
