# Generated by Django 4.2.15 on 2024-12-06 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_theme',
            field=models.CharField(choices=[('#dddcd7', 'Default (Gray)'), ('#e0ecf8', 'Blue'), ('#dbeed5', 'Green'), ('#fde4e4', 'Pink'), ('#f2f4cd', 'Yellow')], default='#dddcd7', max_length=10),
        ),
    ]
