# Generated by Django 5.1.1 on 2024-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_collaborators_alter_board_board_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
