# Generated by Django 4.2.15 on 2024-11-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_category_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(default='def', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
