# Generated by Django 5.1.1 on 2024-12-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_board_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='board',
            name='is_reported',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
