# Generated by Django 5.1.1 on 2024-12-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_is_active_board_is_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots'),
        ),
    ]
