# Generated by Django 4.2.15 on 2024-11-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_notification_has_responded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='has_responded',
            field=models.BooleanField(default=False),
        ),
    ]
