# Generated by Django 4.2.15 on 2024-11-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_notification_has_responded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('invite', 'Invitation'), ('join', 'Joining'), ('remove', 'Removed'), ('accepted', 'Accepted'), ('declined', 'Declined')], max_length=10),
        ),
    ]
