# Generated by Django 4.2.15 on 2024-11-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_notification_notif_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_slug',
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
