# Generated by Django 4.2.15 on 2024-11-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_remove_category_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
